site_name: Goblin Speaks Docs
theme:
  name: material
  features:
    - content.code.copy

nav:
  - Home: index.md
  - Software: software.md
  - Components:
      - Overview: components/overview.md
      - Goblin Speaks Head: components/goblin-speaks-head.md
      - Goblin Speaks Animatronic Body: components/goblin-speaks-body.md
      - Goblin Speaks Card Dispenser: components/goblin-speaks-card-dispenser.md