site_name: Goblin Speaks Fortune Teller Framework
theme:
  name: material
  palette:
    scheme: slate
  features:
    - content.code.copy

nav:
  - Home: index.md
  - Software:
      - Overview: software/overview.md
      - Configuration: software/configuration.md
      - CLI: software/cli.md
      - Raspberry Pi Setup: software/raspberry-pi-setup.md
      - Audio Player: software/audio-player.md
      - Components:
          - Dispenser: software/components/dispenser.md
          - SingleStepperDispenser: software/components/single-stepper.md
      - Plugins: software/plugins.md
  - Physical Components:
      - Overview: components/overview.md
      - Goblin Speaks Animatronic Body: components/goblin-speaks-animatronic-body.md
      - Goblin Speaks Card Dispenser: components/goblin-speaks-card-dispenser.md
      - Goblin Speaks Head: components/goblin-speaks-head.md
