site_name: Goblin Speaks Docs
theme:
  name: material
  palette:
    scheme: slate
  features:
    - content.code.copy

nav:
  - Home: index.md
  - Software:
      - Overview: software/overview.md
      - Raspberry Pi Setup: software/raspberry-pi-setup.md
      - Audio Player: software/audio-player.md
      - Components:
          - Dispenser: software/components/dispenser.md
          - GSCardDispenser: software/components/gs-card.md
      - Contributing: software/contributing.md
  - Physical Components:
      - Overview: components/overview.md
      - Goblin Speaks Animatronic Body: components/goblin-speaks-animatronic-body.md
      - Goblin Speaks Card Dispenser: components/goblin-speaks-card-dispenser.md
      - Goblin Speaks Head: components/goblin-speaks-head.md
