components:
  audio:
    type: audio_player
    pre_show_sound_dir: /opt/goblin-speaks/sounds/pre_show
    # ...
  goblin_body:
    type: animatronic
    class: gs_body
    arm_pin: 0
    # ...
  card_dispenser:
    type: dispenser
    class: gs_card
    pin_1: 17
    # ...

sequence:
  - component: audio
    action: play_sequence
    args:
      sound_types: [pre_show, show, post_show]
    output: duration
  - component: goblin_body
    action: animate
    args:
      duration: $duration
  - component: card_dispenser
    action: dispense
