components:
  goblin_body:
    type: animatronic
    class: gs_body
  card_dispenser:
    type: dispenser
    class: single_stepper
    dispense_steps: 2048
    step_delay: 0.0015

sequence:
  - component: audio
    action: play_sequence
    args:
      sound_types: [pre_show, show, post_show]
    output: duration
  - component: goblin_body
    action: animate
    args:
      duration: $duration
  - component: card_dispenser
    action: dispense
