name: Compile and Auto-Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release-arm:
    runs-on: ubuntu-22.04-arm 
    
    permissions:
      contents: write 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc patchelf build-essential

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka
          pip install -r requirements.txt 

      - name: Compile Python to C
        run: |
          python -m nuitka --standalone \
            --include-package=adafruit_blinka \
            --include-package=adafruit_servokit \
            --include-module=pygame \
            --output-dir=build \
            main.py

      - name: Compress Build
        run: |
          # Compress the directory into a tarball
          tar -czvf goblin-app.tar.gz -C build/main.dist .

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          files: goblin-app.tar.gz
          generate_release_notes: true